package com.example.javaspringbootproject;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

@Controller // This means that this class is a Controller
@RequestMapping(path="/student") // This means URL's start with /demo (after Application path)
public class StudentController {
    @Autowired // This means to get the bean called userRepository
        // Which is auto-generated by Spring, we will use it to handle the data
    private StudentRepository studentRepository;

    // Add – a particular student
    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewStudent (@RequestParam String firstName, @RequestParam String lastName,
                                               @RequestParam String email, @RequestParam String address,
                                               @RequestParam String city, @RequestParam String postal,
                                               @RequestParam String phone){
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Student student = new Student();
        student.setFirstName(firstName);
        student.setLastName(lastName);
        student.setEmail(email);
        student.setAddress(address);
        student.setCity(city);
        student.setPostal(postal);
        student.setPhone(phone);
        studentRepository.save(student);
        return student.getFirstName() + " " + student.getLastName() + " was saved.";
    }

    @PostMapping(path="/add",
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE) // Map ONLY POST Requests
    public @ResponseBody Student addNewStudentObject (@RequestBody Student newStudent){
        return studentRepository.save(newStudent);
    }

    // List – all students
    @GetMapping(path="/list")
    public @ResponseBody Iterable<Student> getAllStudents() {
        // This returns a JSON or XML with the users
        return studentRepository.findAll();
    }

    // View – one student at a time based on id
    @GetMapping(path="/view/{id}")
    public @ResponseBody Student getStudent(@PathVariable Integer id) {
        // This returns a JSON or XML with the users
        return studentRepository.getStudentByStudentId(id);
    }

    @PutMapping(path="/modify",
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody Student modifyStudent(@RequestBody Student modifiedStudent){
        Student student = studentRepository.getStudentByStudentId(modifiedStudent.getStudentId());
        if (student == null){
            throw new ResponseStatusException(HttpStatus.NOT_FOUND);
        }

        student.setFirstName(modifiedStudent.getFirstName());
        student.setLastName(modifiedStudent.getLastName());
        student.setEmail(modifiedStudent.getEmail());
        student.setAddress(modifiedStudent.getAddress());
        student.setCity(modifiedStudent.getCity());
        student.setPostal(modifiedStudent.getPostal());
        student.setPhone(modifiedStudent.getPhone());

        return studentRepository.save(student);
    }

    @DeleteMapping(path="/delete")
    public @ResponseBody String deleteStudent(@RequestParam Integer studentId){
        Student student = studentRepository.getStudentByStudentId(studentId);
        if (student == null){
            throw new ResponseStatusException(HttpStatus.NOT_FOUND);
        }

        studentRepository.delete(student);
        return student.getFirstName() + " " + student.getLastName() + " was removed.";
    }
}